//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        public int DeptId { get; set; }
        public string DeptAdi { get; set; }
    }
}
